"""UCBCKOPTKMI.QEDVSMV.Q.S.QCBDEKBDQBDAIBIWKODIKVQOYDMIDMWCFIBDSVQBADHWIXSIBEYDKBKOYVQVD.TQVDCBOYDRCWFVDRIOODQHD.TIDPOKQB.IG.DQVDOCBADIBCSATDKBJDQVDBC.D.CCDJQHHIWIB.DHWCUDBCWUKOD.IG.DCBIDVTCSOJDKOVCDFBCRDRTK.DOKBASKAID.TIDPOKQB.IG.DQVDRWQ..IBDQBDKVD.TIDHWIXSIBEQIVDCHDOI..IWVDLKWYDHWCUDOKBASKAID.CDOKBASKAIDVCUID.IG.VDKWIDTKWJIWD.CDMWIKFD.TKBDC.TIWVDKBDIGKUPOIDQVD.TIDVIB.IBEID.TIDXSQEFDMWCRBDHCGDNSUPVDCLIWD.TIDOKZYDJCAD.TQVDVIB.IBEIDECB.KQBVDILIWYDOI..IWDCHD.TIDKOPTKMI.DBC.DTIOPQBAD.TIDEWYP.KBKOYV.DACCJDOSEF"""

cipher = "UCBCKOPTKMI.QEDVSMV.Q.S.QCBDEKBDQBDAIBIWKODIKVQOYDMIDMWCFIBDSVQBADHWIXSIBEYDKBKOYVQVD.TQVDCBOYDRCWFVDRIOODQHD.TIDPOKQB.IG.DQVDOCBADIBCSATDKBJDQVDBC.D.CCDJQHHIWIB.DHWCUDBCWUKOD.IG.DCBIDVTCSOJDKOVCDFBCRDRTK.DOKBASKAID.TIDPOKQB.IG.DQVDRWQ..IBDQBDKVD.TIDHWIXSIBEQIVDCHDOI..IWVDLKWYDHWCUDOKBASKAID.CDOKBASKAIDVCUID.IG.VDKWIDTKWJIWD.CDMWIKFD.TKBDC.TIWVDKBDIGKUPOIDQVD.TIDVIB.IBEID.TIDXSQEFDMWCRBDHCGDNSUPVDCLIWD.TIDOKZYDJCAD.TQVDVIB.IBEIDECB.KQBVDILIWYDOI..IWDCHD.TIDKOPTKMI.DBC.DTIOPQBAD.TIDEWYP.KBKOYV.DACCJDOSEF"

placeholder = "\uFFFF"  # unlikely char
swapped = cipher.replace("D", placeholder).replace(".", "D").replace(placeholder, ".")
print(swapped)

"""
K	A
M	B
E	C
J	D
I	E
H	F
A	G
T	H
Q	I
N	J
F	K
O	L
U	M
B	N
C	O
P	P
X	Q
W	R
V	S
D	T
S	U
L	V
R	W
G	X
Y	Y
Z	Z
.	.
"""

substitution = {
    "K": "A",
    "M": "B",
    "E": "C",
    "J": "D",
    "I": "E",
    "H": "F",
    "A": "G",
    "T": "H",
    "Q": "I",
    "N": "J",
    "F": "K",
    "O": "L",
    "U": "M",
    "B": "N",
    "C": "O",
    "P": "P",
    "X": "Q",
    "W": "R",
    "V": "S",
    "D": "T",
    "S": "U",
    "L": "V",
    "R": "W",
    "G": "X",
    "Y": "Y",
    "Z": "Z",
    ".": " "
}

# Step 3: decipher the message
deciphered = ""
for char in swapped:
    if char in substitution:
        deciphered += substitution[char]
    else:
        deciphered += char  

print("\nDecrypted text:\n")
print(deciphered)